import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { AdminCatalogueManager } from "@/components/admin-catalogue-manager";

export default async function AdminPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/account/login"); const { data: profile } = await supabase.from("profiles").select("role,full_name").eq("id", user.id).maybeSingle(); if (!profile || !["staff", "admin"].includes(profile.role)) return <div className="shell auth-wrap"><span className="eyebrow">RESTRICTED AREA</span><h1>Staff access required.</h1><p>Your account is active, but it has not yet been assigned a staff role. In Supabase SQL Editor, update your profile to <code>admin</code> or <code>staff</code>.</p></div>;
  const [{ count: products }, { count: quotes }, { data: categories }, { data: catalogueProducts }] = await Promise.all([supabase.from("products").select("*", { count: "exact", head: true }), supabase.from("quote_requests").select("*", { count: "exact", head: true }).eq("status", "new"), supabase.from("categories").select("*").order("sort_order"), supabase.from("products").select("*, categories(name,slug)").order("created_at", { ascending: false })]);
  return <div className="shell section"><span className="eyebrow">SK TRADERS ADMIN</span><h1 style={{ fontSize: 48 }}>Hello, {profile.full_name || "team"}.</h1><div className="trust" style={{ gridTemplateColumns: "repeat(3,1fr)" }}><div className="trust-item"><span className="trust-icon">□</span><span><b>{products || 0} products</b><small>Catalogue entries</small></span></div><div className="trust-item"><span className="trust-icon">◌</span><span><b>{quotes || 0} new quotes</b><small>Need a response</small></span></div><div className="trust-item"><span className="trust-icon">⌁</span><span><b>{categories?.length || 0} categories</b><small>Catalogue structure</small></span></div></div><AdminCatalogueManager categories={categories || []} initialProducts={catalogueProducts || []}/><p style={{ marginTop: 25 }}><Link className="btn btn-primary" href="/products">View storefront →</Link></p></div>;
}
