"use client";
import { FormEvent, useState } from "react";
import { Category, Product } from "@/lib/types";
import { createClient } from "@/lib/supabase/client";

export function AdminCatalogueManager({ categories, initialProducts }: { categories: Category[]; initialProducts: Product[] }) {
  const [products, setProducts] = useState(initialProducts); const [notice, setNotice] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function addProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setNotice(null); const form = new FormData(event.currentTarget); const input = { category_id: String(form.get("category_id")), name: String(form.get("name")), slug: String(form.get("slug")), sku: String(form.get("sku")).toUpperCase(), short_description: String(form.get("short_description")) || null, voltage: String(form.get("voltage")) || null, moq: Number(form.get("moq")), stock: String(form.get("stock")), price_from: form.get("price_from") ? Number(form.get("price_from")) : null, is_active: true };
    const { data, error } = await createClient().from("products").insert(input).select("*, categories(name,slug)").single(); setSaving(false); if (error) { setNotice(error.message); return; } setProducts(current => [data as Product, ...current]); event.currentTarget.reset(); setNotice("Product created. Add its image and model compatibility in Supabase Table Editor."); }
  async function toggle(product: Product) { const { error } = await createClient().from("products").update({ is_active: !product.is_active }).eq("id", product.id); if (error) { setNotice(error.message); return; } setProducts(current => current.map(item => item.id === product.id ? { ...item, is_active: !item.is_active } : item)); }
  return <><div className="notice">Quick catalogue manager: create a product or hide it from the public catalogue. Use Supabase Storage/Table Editor for product photos and compatibility links.</div><div className="section" style={{ paddingBottom: 30 }}><h2 className="section-title" style={{ fontSize: 31 }}>Add product</h2><form className="form-card" onSubmit={addProduct}><div className="compact-grid"><div><label>Product name</label><input required name="name" placeholder="Example: 48V controller"/></div><div><label>SKU</label><input required name="sku" placeholder="SK-CT-048"/></div></div><div className="compact-grid"><div><label>URL slug</label><input required name="slug" placeholder="48v-controller" pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></div><div><label>Category</label><select required name="category_id"><option value="">Select category</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div></div><div className="compact-grid"><div><label>Voltage / specification</label><input name="voltage" placeholder="48V / 30A"/></div><div><label>MOQ</label><input required name="moq" type="number" min="1" defaultValue="1"/></div></div><div className="compact-grid"><div><label>Stock status</label><select name="stock"><option value="in_stock">In stock</option><option value="limited">Limited stock</option><option value="out_of_stock">Out of stock</option></select></div><div><label>Price from (₹)</label><input name="price_from" type="number" min="0" step="1"/></div></div><label>Short description</label><textarea name="short_description" placeholder="A short, clear dealer-facing description."/><button className="btn btn-primary" disabled={saving} style={{ marginTop: 15 }}>{saving ? "Saving…" : "Create product"}</button>{notice && <p className={notice.includes("created") ? "form-success" : "form-error"}>{notice}</p>}</form></div><h2 className="section-title" style={{ fontSize: 31 }}>Catalogue products</h2><table className="admin-table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Status</th><th/></tr></thead><tbody>{products.map(product => <tr key={product.id}><td>{product.name}</td><td>{product.sku}</td><td>{product.categories?.name || "—"}</td><td>{product.is_active ? "Live" : "Hidden"}</td><td><button className="btn btn-ghost" onClick={() => toggle(product)}>{product.is_active ? "Hide" : "Publish"}</button></td></tr>)}</tbody></table></>;
}
