"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const router = useRouter(); const [status, setStatus] = useState<string | null>(null); const [loading, setLoading] = useState(false); const register = mode === "register";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setStatus(null); const form = new FormData(event.currentTarget); const email = String(form.get("email")); const password = String(form.get("password")); const supabase = createClient(); const { error } = register ? await supabase.auth.signUp({ email, password, options: { data: { full_name: form.get("full_name") } } }) : await supabase.auth.signInWithPassword({ email, password }); setLoading(false); if (error) { setStatus(error.message); return; } if (register) { setStatus("Account created. Check your inbox if email confirmation is enabled, then sign in."); } else { router.push("/"); router.refresh(); } }
  return <div className="shell auth-wrap"><span className="eyebrow">SK TRADERS ACCOUNT</span><h1>{register ? "Create account" : "Welcome back"}</h1><p>{register ? "Save your contact details and make future quote requests faster." : "Sign in to your SK Traders account."}</p><form className="form-card" onSubmit={submit}>{register && <><label htmlFor="full_name">Full name</label><input id="full_name" name="full_name" required/></>}<label htmlFor="email">Email address</label><input id="email" name="email" type="email" required/><label htmlFor="password">Password</label><input id="password" name="password" type="password" minLength={6} required/><button className="btn btn-primary" disabled={loading} style={{ marginTop: 18 }} type="submit">{loading ? "Please wait…" : register ? "Create account" : "Sign in"}</button>{status && <p className={status.includes("created") ? "form-success" : "form-error"}>{status}</p>}</form><p>{register ? <>Already have an account? <Link href="/account/login"><u>Sign in</u></Link></> : <>New to SK Traders? <Link href="/account/register"><u>Create an account</u></Link></>}</p></div>;
}
