"use client";
import { ChangeEvent, FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function PhotoPartFinder() {
  const [file, setFile] = useState<File | null>(null); const [status, setStatus] = useState<string | null>(null); const [sending, setSending] = useState(false);
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { const next = event.target.files?.[0] || null; if (next && (!next.type.startsWith("image/") || next.size > 5 * 1024 * 1024)) { setFile(null); setStatus("Use a JPG, PNG or WebP image up to 5 MB."); return; } setStatus(null); setFile(next); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!file) { setStatus("Choose a clear photo of the part first."); return; } setSending(true); setStatus(null); const form = new FormData(event.currentTarget); const extension = file.name.split(".").pop() || "jpg"; const path = `anonymous/${crypto.randomUUID()}.${extension}`; const supabase = createClient(); const { error: uploadError } = await supabase.storage.from("part-photos").upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) { setStatus(uploadError.message); setSending(false); return; } const { error } = await supabase.from("part_photo_requests").insert({ full_name: String(form.get("full_name")), phone: String(form.get("phone")), scooter_details: String(form.get("scooter_details") || ""), note: String(form.get("note") || ""), image_path: path }); setSending(false); if (error) { setStatus(error.message); return; } event.currentTarget.reset(); setFile(null); setStatus("Photo sent. Our parts team will identify it and reply on WhatsApp."); }
  return <section className="photo-finder"><div className="shell photo-finder-grid"><div><span className="eyebrow">CAN’T FIND THE PART?</span><h2>Send a photo.<br/><em>We’ll help identify it.</em></h2><p>Many parts are easier to identify by appearance than by SKU. Send a clear photo and your scooter details; our team will check it before quoting.</p></div><form className="photo-form" onSubmit={submit}><label className="photo-upload"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseFile}/><span>⌁</span><b>{file ? file.name : "Upload part photo"}</b><small>JPG, PNG or WebP · up to 5 MB</small></label><div className="compact-grid"><input required name="full_name" placeholder="Your name *"/><input required name="phone" placeholder="WhatsApp number *"/></div><input name="scooter_details" placeholder="Scooter brand, model, variant (if known)"/><textarea name="note" placeholder="Any markings, voltage or connector details?"/><button disabled={sending} className="btn btn-primary">{sending ? "Sending photo…" : "Send photo for identification →"}</button>{status && <p className={status.includes("sent") ? "form-success" : "form-error"}>{status}</p>}</form></div></section>;
}
