"use client";
import { FormEvent, useMemo, useState } from "react";
import { ScooterModel } from "@/lib/types";
import { useRouter } from "next/navigation";

export function ProductFinder({ models }: { models: ScooterModel[] }) {
  const router = useRouter(); const brands = useMemo(() => [...new Set(models.map(model => model.brand))], [models]); const [brand, setBrand] = useState(""); const [model, setModel] = useState(""); const [query, setQuery] = useState(""); const visibleModels = models.filter(item => item.brand === brand); const selected = visibleModels.find(item => item.id === model);
  function showCompatible(event: FormEvent) { event.preventDefault(); if (!model) return; router.push(`/products?model=${model}`); }
  function search(event: FormEvent) { event.preventDefault(); const value = query.trim(); router.push(value ? `/products?q=${encodeURIComponent(value)}` : "/products"); }
  return <section className="finder finder-priority" id="find-part"><div className="shell"><div className="finder-heading"><span className="eyebrow">SMART PARTS FINDER</span><h2>Find parts for your<br/>E-scooty.</h2><p>Choose the vehicle first and see only compatible parts—no guessing, no wrong orders.</p></div><form className="fitment-form" onSubmit={showCompatible}><div className="fitment-step"><small>01</small><label>Brand<select value={brand} onChange={event => { setBrand(event.target.value); setModel(""); }}><option value="">Select brand</option>{brands.map(item => <option key={item}>{item}</option>)}</select></label></div><span className="flow-arrow">→</span><div className="fitment-step"><small>02</small><label>E-scooty model<select disabled={!brand} value={model} onChange={event => setModel(event.target.value)}><option value="">Select model</option>{visibleModels.map(item => <option value={item.id} key={item.id}>{item.model}</option>)}</select></label></div><span className="flow-arrow">→</span><div className="fitment-step variant"><small>03</small><label>Variant / generation<output>{selected?.model_year || (selected ? "Standard variant" : "Select model first")}</output></label></div><button disabled={!model} className="btn btn-primary">Show compatible parts →</button></form><div className="finder-or"><span/> OR SEARCH A PART DIRECTLY <span/></div><form className="search-box finder-search" onSubmit={search}><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by part name, SKU or part number"/><button>Search catalogue</button></form></div></section>;
}
